# Type stub for peclet.halo._halo — GENERATED by `python -m nanobind.stubgen -m peclet.halo._halo -o python/packaging/_halo.pyi`
# (PYTHONPATH at the python build tree). Do not hand-edit; regenerate after changing halo_bindings.cpp. The one
# post-processing step: build_toolchain's value (the building compiler) is replaced by its type.
"""
peclet.halo extension: the Lagrangian particle halo (ORB block decomposition, particle migration, ghosts and count-weighted rebalancing) over MPI_COMM_WORLD.
"""

from collections.abc import Sequence
from typing import Annotated

import numpy
from numpy.typing import NDArray


build_toolchain: str

class ParticleMigrator:
    """
    Lagrangian particle migration over an ORB block decomposition of the box [origin, origin+extent) binned on `cells` cells per axis (MPI_COMM_WORLD). Positions are (N,3) float64, the per-particle payload a 2-D (N,K) float64 array with the same N (pack velocity, id, ... into the K columns).

    MPI must already be initialized (import mpi4py.MPI first); the module never calls MPI_Init/Finalize. Construction does not communicate. migrate, rebalance and gather_ghosts are collective over MPI_COMM_WORLD: every rank calls them, in the same order, even with no particles.
    """

    def __init__(self, origin: Sequence[float], extent: Sequence[float], cells: Sequence[int], periodic: Sequence[bool]) -> None:
        """
        origin: lower corner of the box; extent: its side lengths; cells: decomposition cells per axis (the ORB bins particles on this grid); periodic: per axis.
        """

    def migrate(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')]) -> tuple:
        """
        Reassign every particle to the rank owning its (wrapped) position. Collective. Returns this rank's (positions (M,3), payload (M,K)) after the exchange.
        """

    def rebalance(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')]) -> tuple:
        """
        Re-decompose by particle count (weighted ORB) so each rank holds a near-equal share, then migrate. Pure redistribution (count/payload preserved); the partition is updated in place, so later owner_of/migrate/gather_ghosts calls use it. Collective. Returns this rank's (positions (M,3), payload (M,K)).
        """

    def gather_ghosts(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')], rcut: float) -> tuple:
        """
        Copies of the particles OTHER ranks own that lie within distance rcut of this rank's block, each at its periodic image nearest the block. A rank's own periodic images are not included (np=1 gets none; ParticleHalo.build(include_periodic_self=True) covers that). Collective. Returns (ghost positions (G,3), ghost payload (G,K)); the inputs are not modified.
        """

    def wrap_position(self, x: Sequence[float]) -> list[float]:
        """
        Periodic-wrapped / boundary-clamped position for x (the canonical image).
        """

    def cell_of(self, x: Sequence[float]) -> list[int]:
        """Global decomposition cell index (i,j,k) containing x (after wrap)."""

    def last_sent(self) -> int:
        """Particles shipped by this rank in the last migrate()."""

    def last_received(self) -> int:
        """Particles absorbed by this rank in the last migrate()."""

    def owner_of(self, x: Sequence[float]) -> int:
        """
        Rank that owns the block containing position x (after periodic wrap / boundary clamp).
        """

    @property
    def rank(self) -> int:
        """This process's MPI rank."""

class ParticleHalo:
    """
    Persistent owner<->ghost particle halo over the same decomposition as ParticleMigrator: build() the correspondence once, then forward/reverse (N,3) float64 fields each step while the owned particles and their order stay fixed. MPI must already be initialized; build, forward_positions, forward and reverse communicate, so every rank calls them.
    """

    def __init__(self, origin: Sequence[float], extent: Sequence[float], cells: Sequence[int], periodic: Sequence[bool]) -> None:
        """
        origin: lower corner of the box; extent: its side lengths; cells: decomposition cells per axis (the ORB bins particles on this grid); periodic: per axis.
        """

    def build(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], rcut: float, include_periodic_self: bool = False) -> int:
        """
        Establish the owner<->ghost correspondence from this rank's owned positions (N,3): a ghost here is a copy of a particle another rank owns within distance rcut of this rank's block. include_periodic_self also emits a rank's own periodic images (needed on an undecomposed periodic axis, e.g. at np=1). Collective. Returns the ghost count G.
        """

    def forward_positions(self, owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        owned (N,3) -> ghost (G,3), adding each ghost's periodic image shift: use for positions. N must be the count passed to the last build().
        """

    def forward(self, owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        owned (N,3) -> ghost (G,3) copied verbatim: use for velocities and other fields without an image shift.
        """

    def reverse(self, ghost: Annotated[NDArray[numpy.float64], dict(order='C')], owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        ghost (G,3) contributions summed back onto their owners: returns a new (N,3) array, owned + the reversed contributions (e.g. forces on ghosts); `owned` is not modified.
        """

    def owner_of(self, x: Sequence[float]) -> int:
        """
        Rank that owns the block containing position x (after periodic wrap / boundary clamp).
        """

    @property
    def num_ghost(self) -> int:
        """
        Ghost particles this rank receives (G), as established by the last build().
        """

    @property
    def num_owned(self) -> int:
        """Owned particles (N) this rank passed to the last build()."""

    @property
    def rank(self) -> int:
        """This process's MPI rank."""
