# Type stub for peclet.core.amr — GENERATED by `python -m nanobind.stubgen -m peclet.core.amr -o packaging/core_amr.pyi`
# (PYTHONPATH at the python build tree). Do not hand-edit; regenerate after changing amr_bindings.cpp.
"""
core adaptive-mesh-refinement: per-block BlockOctree (serial) and DistributedOctree (MPI ORB) for the mesh, plus the device (Kokkos) AmrFlow cut-cell Stokes/Navier-Stokes solver. Build a graded octree, refine to an SDF surface, read leaf geometry + per-leaf fields as numpy, load-rebalance, gather face neighbours, export VTU, and run the flow step on device.
"""

from collections.abc import Callable, Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


def finalize() -> None:
    """
    Release every live object and zero-copy array of this module, then Kokkos::finalize() (deterministic teardown; also run automatically at interpreter exit). Idempotent. After it, the module's solver objects and *_view arrays must not be used.
    """

execution_space: str = 'OpenMP'

def spacing_from_extent(extent: Sequence[float], root_cells: Sequence[int], lmax: int) -> float:
    """
    The finest cell width h0 = extent / (root_cells * 2**lmax) of a PHYSICAL domain — the one place an AMR spacing is computed, so no caller writes one (see suite/docs/PHYSICAL_UNITS_PLAN.md). Returns ONE number, so it raises when the extent does not give cubic cells — use `spacings_from_extent` for a box mesh.
    """

def spacings_from_extent(extent: Sequence[float], root_cells: Sequence[int], lmax: int) -> list[float]:
    """
    The finest cell size (dx, dy, dz) = extent / (root_cells * 2**lmax), PER AXIS. The anisotropic form of `spacing_from_extent`: it accepts any positive extent, because the octree's cells are boxes (core/docs/amr_anisotropic.md).
    """

class Octree:
    """
    Serial single-block adaptive octree with a world placement (origin + finest spacing per axis). Leaves are addressed in Z-order slot order; every per-leaf array is indexed by that slot.
    """

    def __init__(self, cells: Sequence[int], *, lmax: int = 0, origin: Sequence[float] = [0.0, 0.0, 0.0], spacing: float | Sequence[float] | None = None, extent: Sequence[float] | None = None) -> None:
        """
        Build a uniform octree resolving `cells` FINEST cells per axis, refinable `lmax` levels (the root brick is cells/2**lmax root cells, which must divide exactly; lmax=0 is a uniform grid). `origin` is the block's lower corner. Every argument after `cells` is keyword-only.

        State the domain PHYSICALLY with `extent` = the box side lengths: the cell size is then extent/cells PER AXIS and the caller never writes a spacing. Alternatively give `spacing` (one number for cubic cells, or (dx, dy, dz)); default 1. Passing both raises.

        The cells are BOXES (core/docs/amr_anisotropic.md): any positive extent is accepted, the octree refines by 2 on every axis, and every level inherits the root aspect ratio. Read the three numbers back from `.spacing`.
        """

    @property
    def cells(self) -> list[int]:
        """Finest-level cell counts per axis (root*2**lmax)."""

    @property
    def extent(self) -> list[float]:
        """Block side lengths in world units (cells*spacing)."""

    @property
    def spacing(self) -> list[float]:
        """Finest cell size (dx, dy, dz), per axis. Equal on a cubic octree."""

    @property
    def num_leaves(self) -> int:
        """Number of leaves (Z-order slots)."""

    @property
    def lmax(self) -> int:
        """Root-cell level (max refinement depth)."""

    @property
    def origin(self) -> list[float]:
        """Block lower corner in world coordinates."""

    def is_balanced(self) -> bool:
        """
        True iff every face-adjacent leaf pair differs by at most one level (2:1).
        """

    def centers(self) -> NDArray[numpy.float64]:
        """Leaf world centres, (num_leaves, 3) float64."""

    def sizes(self, axis: int = 0) -> NDArray[numpy.float64]:
        """
        Leaf world widths along `axis`: spacing[axis]*2**level, (num_leaves,) float64. A leaf is a BOX, so `axis` selects which of the three widths (0 by default, which is THE width on a cubic octree).
        """

    def levels(self) -> NDArray[numpy.int32]:
        """Leaf refinement levels, (num_leaves,) int32 (0 = finest)."""

    def codes(self) -> NDArray[numpy.uint64]:
        """Leaf block-local Morton origin codes, (num_leaves,) uint64."""

    def find(self, x: Sequence[float]) -> int:
        """
        Index of the leaf containing world point x=(x,y,z), or -1 if outside the block.
        """

    def refine_to_sphere(self, center: Sequence[float], radius: float, target_level: int = 0, band: float = 1.0, balance: bool = True) -> int:
        """
        Refine leaves the sphere surface passes through (plus `band` cells) down to target_level; optionally restore 2:1 balance. Returns the number of refinements performed.
        """

    def refine_to_sdf(self, sdf: Callable[[float, float, float], float], target_level: int = 0, band: float = 1.0, balance: bool = True) -> int:
        """
        Refine toward an arbitrary signed-distance field given as a callable f(x,y,z)->distance (suite sign: <0 inside solid), down to target_level. Returns refinements performed.
        """

    def refine_to_sdf_graded(self, sdf: Callable[[float, float, float], float], target_level: Callable[[float, float, float], int], band: float = 2.0, balance: bool = True) -> int:
        """
        GRADED surface refinement (the mixed-level cut band, docs/amr_mixed_level_cut_band_plan.md §7): `target_level` is a callable f(x,y,z)->level giving the COARSEST acceptable level at a world point (0 = finest), so cut cells end up at SEVERAL levels — fine in throats/contacts, coarse on smooth caps. The band margin is measured in cells of the level being created (not in the finest spacing as in refine_to_sdf). Requires Flow.set_ghost_sampled(True) — the classic overlay contracts a uniform finest band and raises on these level jumps. Returns refinements performed.
        """

    def refine_to_gap_floor(self, sdf: Callable[[float, float, float], float], gap: Callable[[float, float, float], float], coarsest_level: int, n: float = 4.0, band: float = 2.0, balance: bool = True) -> int:
        """
        refine_to_sdf_graded driven by the plan's GAP-WIDTH FLOOR (§7 criterion 1): the target level at a point is the coarsest L with n*h_L <= gap(x), clamped to [0, coarsest_level]. `gap` is the local fluid-gap proxy f(x,y,z)->width — for a sphere packing the two-closest-surfaces sum d1+d2; a medial-axis or peclet.pnm throat-radius field substitutes verbatim. n=4 per the M1/M2 measurements. This is the AMReX multi-valued-cell rule inverted: coarsening never merges or disconnects fluid.
        """

    def refine_leaf(self, i: int) -> bool:
        """
        Split leaf `i` into its 8 children; returns True if it was split (level>0).
        """

    def balance(self) -> int:
        """
        Enforce 2:1 graded balance to a fixpoint; returns refinements performed.
        """

    def lohner_indicator(self, field: Annotated[NDArray[numpy.float64], dict(order='C')], eps: float = 0.01) -> NDArray[numpy.float64]:
        """
        Löhner normalized-second-difference feature indicator E in [0,1] per leaf from a scalar field (num_leaves,); large E = steep feature (refine), small = smooth (coarsen).
        """

    def adapt(self, field: Annotated[NDArray[numpy.float64], dict(order='C')], refine_thresh: float, coarsen_thresh: float, finest_level: int = 0, eps: float = 0.01, linear: bool = True) -> NDArray[numpy.float64]:
        """
        Solution-adaptive step (Löhner-driven): refine where the indicator > refine_thresh (to finest_level), coarsen sibling groups all < coarsen_thresh, 2:1-balance, and conservatively remap `field`. MUTATES the octree in place; returns the remapped field (M,). `linear` uses minmod-limited prolongation (else piecewise-constant).
        """

    def write_vtu(self, path: str, name: str, field: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None:
        """
        Write the octree + a per-leaf scalar field (num_leaves,) as a VTK UnstructuredGrid (.vtu, ASCII, one cell per leaf), openable in ParaView.
        """

class Poisson:
    """
    Cell-centered finite-volume Poisson solver (L u = rhs) on an Octree, by a geometric-multigrid V-cycle. L is the conservative two-point FV Laplacian (suite sign). The hierarchy snapshots the octree at construction; per-leaf arrays are (num_leaves,) float64 in Z-order slots.
    """

    def __init__(self, octree: Octree, periodic: bool = True) -> None:
        """
        Build the multigrid hierarchy from `octree`. periodic=True solves the singular periodic problem (constant null space removed each cycle).
        """

    @property
    def num_leaves(self) -> int:
        """Leaves on the finest level."""

    @property
    def num_levels(self) -> int:
        """Number of multigrid levels."""

    def apply(self, u: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        L applied to u (the FV Laplacian); use b = apply(u_exact) to manufacture a RHS. (num_leaves,) -> (num_leaves,).
        """

    def residual(self, u: Annotated[NDArray[numpy.float64], dict(order='C')], rhs: Annotated[NDArray[numpy.float64], dict(order='C')]) -> float:
        """Volume-weighted L2 residual norm sqrt(sum V*(rhs - L u)^2)."""

    def solve(self, rhs: Annotated[NDArray[numpy.float64], dict(order='C')], x0: Annotated[NDArray[numpy.float64], dict(order='C')] | None = None, cycles: int = 20, pre: int = 2, post: int = 2, tol: float = 0.0) -> tuple:
        """
        Solve L u = rhs with up to `cycles` V-cycles (pre/post Gauss-Seidel sweeps), from x0 or 0, stopping once residual <= tol (tol<=0 disables). Returns (u (num_leaves,), final_residual, cycles_done).
        """

class Flow:
    """
    Collocated incompressible Stokes/Navier-Stokes step on an Octree with a cut-cell immersed boundary (no-slip on an SDF solid). step() = implicit viscous momentum predictor + Almgren-Bell-Colella rotational projection. Drive with a body force and iterate to steady state; velocities are per-leaf (num_leaves,) in Z-order slots.
    """

    @overload
    def __init__(self, octree: Octree, density: float = 1.0, viscosity: float = 1.0, dt: float = 1000000.0) -> None:
        """
        Create a flow on `octree` with the given density, viscosity and time step. A large dt drives straight to the steady (Stokes) solution. The octree is borrowed by reference.
        """

    @overload
    def __init__(self, octree: DistributedOctree, density: float = 1.0, viscosity: float = 1.0, dt: float = 1000000.0) -> None:
        """
        DISTRIBUTED (mpi4py, collective): run this solver on one ORB block of a DistributedOctree — the whole step (momentum, pressure, overlays, adaptivity) then executes multi-rank through the ±2 leaf ghost registry. Per-leaf arrays are this rank's LOCAL leaves. setSolid/step/project/begin_adapt/finish_adapt/rebalance_mpi are collective. np=1 is bit-identical to the single-rank constructor.
        """

    def rebalance_mpi(self, sdf: Callable[[float, float, float], float]) -> None:
        """
        DISTRIBUTED: weighted-ORB load rebalance — migrates the leaves WITH the state (u, p) to the new owners and rebuilds every solver structure (collective). num_leaves is refreshed.
        """

    @property
    def num_leaves(self) -> int:
        """Number of leaves."""

    def set_solid(self, sdf: Callable[[float, float, float], float]) -> None:
        """
        Build the cut-cell operators from a signed-distance callable f(x,y,z) (>0 fluid, <0 solid) and zero the fields. Call before stepping; re-call to change the geometry.
        """

    def set_solid_spheres(self, centers: Annotated[NDArray[numpy.float64], dict(order='C', writable=False)], radii: Annotated[NDArray[numpy.float64], dict(order='C', writable=False)], periodic: bool = True) -> None:
        """
        set_solid for a UNION OF SPHERES, evaluated natively instead of through a Python callback — the porous-media geometry. `centers` is (M,3), `radii` is (M,) or (1,); `periodic` uses the minimum-image convention over the octree's own box extent. Prefer this to set_solid at bed scale: set_solid samples the SDF tens of times per leaf (operator build, overlay classification at virtual positions, the openness probe), so a Python callback dominates everything else — measured >1h43m of pure numpy on an 11.35M-leaf 180-sphere bed before the GPU ran a single kernel.
        """

    def set_body_force(self, fx: float, fy: float, fz: float) -> None:
        """
        Set the per-volume body force (e.g. a pressure gradient) driving the flow.
        """

    def set_advection(self, on: bool) -> None:
        """Enable explicit momentum advection (Navier-Stokes); off = Stokes."""

    def set_ghost_gradient(self, on: bool) -> None:
        """
        Directional ghost cell-gradient on cut cells for the pressure predictor and the projection's cell correction (2nd-order one-sided, never reads decoupled solid pressure — removes the gauge-dependent O(1/h) cut-cell gradient error of the plain ABC gradient). The aperture projection itself is unchanged. Call before set_solid.
        """

    def set_aperture_order(self, order: int) -> None:
        """
        Aperture estimator for the (fallback) aperture projection: 2 = analytic marching-squares (DEFAULT since 2026-08-26), 1 = legacy one-sample model. Call before set_solid.
        """

    def set_ghost_projection(self, on: bool, matrix_order: int = 2, rhs_order: int = 2) -> None:
        """
        DEFAULT since 2026-08-25 (AUTO: ghost, with an aperture fallback + stderr notice when the finest band is too thin): the fluid-only constraint scheme — family-free, unconditionally stable, protocol-independent (flow's attractor-campaign verdicts; == flow's set_collocated_scheme('ghost')). FULL directional ghost-cell projection (the AMR port): binary-openness pressure operator + wall-anchored closure overlay on the finest-band rows, MG-preconditioned BiCGStab, ghost-closed divergence constraint; implies set_ghost_gradient. (matrix_order, rhs_order) closure orders: (2, 2) default and the only pair cleared for production — the (1, 2) mixed form is march-UNSTABLE above ~2000 spheres (flow hardening Phase A), kept callable for parity records only. Raises if the finest band is too thin (a closure would cross a 2:1 boundary). Call before set_solid.
        """

    def set_ghost_sampled(self, on: bool) -> None:
        """
        MIXED-LEVEL CUT BAND (docs/amr_mixed_level_cut_band_plan.md): allow cut cells at MULTIPLE octree levels — the finest-band contract is dropped. Chain entries that cross a 2:1 boundary become degree-2 LS virtual samples at the uniform closure positions (identity weights at same level, so a uniform finest band is BIT-IDENTICAL to set_ghost_sampled(False)); face classification uses the level-aware canonical openness; the momentum xi-row seam correction and the wall-aware C/F tangential fallback ride along. Implies the ghost projection (engages when the resolved scheme is ghost — the AUTO default or an explicit set_ghost_projection(True)). Single-rank only (the distributed sample halo is a later rung). Call before set_solid.
        """

    def set_pressure(self, values: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None:
        """
        Write the accumulated rotational pressure from a (num_leaves,) array — restart, or re-accumulation policies after finish_adapt (at steady-state dt the transferred p is the load-bearing state; zeroing it after a coarsening adapt lets it re-accumulate cleanly).
        """

    def set_dt(self, dt: float) -> None:
        """
        Change the time step. dt is BAKED INTO the momentum operator at build time (idiag = rho/dt), so a set_dt must be followed by set_solid or the operator stays stale. set_solid reallocates and zeroes u and p, so a dt SWITCH mid-march is: read velocity()/pressure() -> set_dt -> set_solid -> set_velocity()/set_pressure(). That sequence is the dt-cycling protocol of the attractor-family batteries.
        """

    def begin_adapt(self) -> None:
        """
        Snapshot the octree topology + (u, p) ahead of an external mesh mutation (adapt / refine_to_sphere / refine_to_sdf / balance on the SAME Octree object). Pair with finish_adapt.
        """

    def finish_adapt(self, sdf: Callable[[float, float, float], float]) -> None:
        """
        Rebuild the solver on the mutated octree and conservatively transfer the snapshotted u and p onto it (minmod-limited linear remap). `sdf` is re-sampled on the new leaves (pass the same geometry callable as set_solid); keep the cut band at the finest level on the new mesh (re-run refine_to_sdf on the geometry band after a solution-driven adapt). The advecting face field restarts from the cell average for one step.
        """

    def set_cf_scheme(self, scheme: int) -> None:
        """
        Coarse/fine (2:1) interface scheme: 0 = standard two-point flux (default, 1st-order at level boundaries), 1 = Martin-Cartwright tangential quadratic (2nd-order; applied to the momentum diffusion, the divergence constraint, and the pressure gradients — the pressure matrix/MG stays standard, which does not move the steady solution). Works with both the aperture and the ghost projection. Call before set_solid.
        """

    def set_advection_scheme(self, scheme: int) -> None:
        """
        High-order advection flux: 0 = second-order upwind (default), 1 = Koren TVD.
        """

    def set_implicit_advection(self, on: bool) -> None:
        """
        Implicit first-order-upwind deferred-correction advection (default on): unconditionally stable. Off = fully explicit high-order advection.
        """

    def set_momentum_mg(self, on: bool) -> None:
        """
        Use the Galerkin velocity multigrid as the momentum solve preconditioner (default on; makes the momentum solve scale with resolution). Call before set_solid.
        """

    def set_momentum_gs(self, on: bool) -> None:
        """
        Use the symmetric multicolour Gauss-Seidel smoother in the momentum multigrid (default off = weighted Jacobi). Call before set_solid.
        """

    def set_velocity_mg_staircase(self, on: bool) -> None:
        """
        Use the rediscretised staircase velocity-MG instead of Galerkin (default off).
        """

    def set_momentum_mg_solver(self, on: bool) -> None:
        """
        Solve the momentum predictor with the velocity-MG as the solver (no Krylov), mirroring flow's velocity solve (default off = BiCgStab with the MG as preconditioner).
        """

    def set_outer_iterations(self, n: int, tol: float = 1e-06) -> None:
        """
        Picard outer iterations over the lagged advection per step (default 1).
        """

    def step(self, mom_iters: int = 100, pres_iters: int = 60) -> None:
        """
        Advance one collocated projection step on device: `mom_iters` momentum solver iterations (BiCGStab/MG), `pres_iters` pressure MG-PCG iterations.
        """

    def velocity(self, component: int) -> NDArray[numpy.float64]:
        """Per-leaf velocity component (0=x,1=y,2=z), (num_leaves,) float64."""

    def velocities(self) -> NDArray[numpy.float64]:
        """All three velocity components, (num_leaves, 3) float64."""

    def is_fluid(self) -> NDArray[numpy.bool_]:
        """Per-leaf fluid mask (False in the solid), (num_leaves,) bool."""

    def divergence_norm(self) -> float:
        """
        Volume-weighted L2 norm of the residual cell divergence (projection-quality diagnostic).
        """

    def divergence_norm_face(self) -> float:
        """
        L2 norm of the divergence of the ABC divergence-free FACE field (≈ pressure-solve residual, far below divergence_norm — including across 2:1 interfaces).
        """

    def pressure(self) -> NDArray[numpy.float64]:
        """Per-leaf pressure (incremental-rotational p), (num_leaves,) float64."""

    def face_field(self) -> NDArray[numpy.float64]:
        """
        ABC divergence-free FACE velocity, one value per CSR (sub)face (conservative flux / streamline post-processing).
        """

    def set_velocity(self, component: int, values: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None:
        """
        Write velocity component c (0=x,1=y,2=z) from a (num_leaves,) array — initial conditions, restart, or warm-start. Call before step()/project().
        """

    def project(self, pres_iters: int = 60) -> None:
        """
        Pressure projection only (no momentum solve) — project an externally-set velocity field to divergence-free. Returns nothing; read the result via velocity()/velocities().
        """

    def last_mom_iters(self) -> int:
        """
        Total momentum BiCGStab iterations (summed over the 3 components) of the last step.
        """

    def last_pres_iters(self) -> int:
        """Pressure PCG iterations of the last step."""

    def last_outer_iters(self) -> int:
        """
        Picard outer iterations actually run in the last step (1 unless set_outer_iterations(>1)).
        """

class DistributedOctree:
    """
    MPI octree: an ORB block decomposition of a global root grid (one BlockOctree per rank, over MPI_COMM_WORLD). Construct it collectively; refine/balance/rebalance/face_neighbor_gather are collective. Per-leaf arrays describe THIS rank's local block in global world coordinates.
    """

    def __init__(self, cells: Sequence[int], *, lmax: int = 0, origin: Sequence[float] = [0.0, 0.0, 0.0], spacing: float | Sequence[float] | None = None, periodic: Sequence[bool] = [True, True, True], extent: Sequence[float] | None = None) -> None:
        """
        Decompose a global grid of `cells` FINEST cells per axis (root cells = cells/2**lmax, each `lmax` levels deep) across the ranks of MPI_COMM_WORLD via ORB. `origin` places the global grid; `periodic` per axis. Every argument after `cells` is keyword-only.

        State the domain PHYSICALLY with `extent` = the global box side lengths; the cell size is then extent/cells PER AXIS. Alternatively give `spacing` (one number or (dx, dy, dz)); default 1. Passing both raises. Read the three numbers back from `.spacing`.
        """

    @property
    def rank(self) -> int:
        """This process's MPI rank."""

    @property
    def size(self) -> int:
        """Number of ranks (blocks)."""

    @property
    def num_leaves(self) -> int:
        """Leaves owned by this rank."""

    @property
    def lmax(self) -> int:
        """Root-cell level."""

    @property
    def cells(self) -> list[int]:
        """
        GLOBAL finest-level cell counts per axis (global root cells * 2**lmax).
        """

    @property
    def extent(self) -> list[float]:
        """Global box side lengths in world units (cells*spacing)."""

    @property
    def origin(self) -> list[float]:
        """Global lower corner in world coordinates."""

    @property
    def spacing(self) -> list[float]:
        """Finest cell size (dx, dy, dz), per axis."""

    @property
    def block_origin_root(self) -> list[int]:
        """This rank's block lower corner, in global root-cell coordinates."""

    @property
    def block_brick(self) -> list[int]:
        """This rank's block size in root cells per axis."""

    @property
    def global_root_size(self) -> list[int]:
        """Global grid size in root cells per axis."""

    def centers(self) -> NDArray[numpy.float64]:
        """
        Local leaf world centres, (num_leaves, 3) float64 (global coordinates).
        """

    def sizes(self, axis: int = 0) -> NDArray[numpy.float64]:
        """
        Local leaf world widths along `axis`, (num_leaves,) float64 (see Octree.sizes).
        """

    def levels(self) -> NDArray[numpy.int32]:
        """Local leaf levels, (num_leaves,) int32."""

    def codes(self) -> NDArray[numpy.uint64]:
        """Local leaf block-local Morton origin codes, (num_leaves,) uint64."""

    def refine_to_sphere(self, center: Sequence[float], radius: float, target_level: int = 0, band: float = 1.0, balance: bool = True) -> int:
        """
        Refine the local block toward a GLOBAL sphere surface down to target_level, then (if balance) restore cross-block 2:1 balance collectively. Returns the local count.
        """

    def refine_to_sdf(self, sdf: Callable[[float, float, float], float], target_level: int = 0, band: float = 1.0, balance: bool = True) -> int:
        """
        Refine the local block toward an arbitrary GLOBAL surface given as a callable f(x,y,z)->distance (suite sign: <0 inside solid) — the distributed analogue of Octree.refine_to_sdf, for rings / packed beds / any non-sphere geometry. Collective when balance=True.
        """

    def balance(self) -> int:
        """
        Restore cross-block 2:1 graded balance (collective). Returns this rank's refinements.
        """

    def rebalance(self, fields: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        Re-decompose by leaf count (weighted ORB) and migrate leaves + their fields. `fields` is (num_leaves, K) float64; returns this rank's (M, K) columns after migration. Pure redistribution; the partition is updated in place (collective).
        """

    def face_neighbor_gather(self, field: Annotated[NDArray[numpy.float64], dict(order='C')], sentinel: float = 0.0) -> NDArray[numpy.float64]:
        """
        For each local leaf, the field value across each of its 6 faces, gathered over the owner-based halo. `field` is (num_leaves,); returns (num_leaves, 6) laid out [+x,-x,+y,-y,+z,-z]; domain boundaries carry `sentinel` (collective).
        """

    def lohner_indicator(self, field: Annotated[NDArray[numpy.float64], dict(order='C')], eps: float = 0.01) -> NDArray[numpy.float64]:
        """
        Löhner feature indicator per local leaf, evaluated across the owner-based halo so cross-block neighbours count exactly as in a whole-domain solve. `field` is (num_leaves,); returns (num_leaves,) (collective).
        """

    def adapt(self, field: Annotated[NDArray[numpy.float64], dict(order='C')], refine_thresh: float, coarsen_thresh: float, finest_level: int = 0, eps: float = 0.01, linear: bool = True) -> NDArray[numpy.float64]:
        """
        Distributed solution-adaptive step (Löhner-driven): refine/coarsen each block, restore cross-block 2:1 balance, and conservatively remap `field` (num_leaves,) onto the new local mesh. MUTATES the octree in place (keeping ORB ownership); returns the remapped local field (M,). Bit-identical across rank counts (collective).
        """

    def write_vtu(self, path: str, name: str, field: Annotated[NDArray[numpy.float64], dict(order='C')]) -> None:
        """
        Write this rank's local octree + a per-leaf scalar (num_leaves,) as a .vtu (one file per rank; combine in ParaView).
        """
