# Type stub for peclet.core.mpi — GENERATED by `python -m nanobind.stubgen -m peclet.core.mpi -o packaging/core_mpi.pyi`
# (PYTHONPATH at the python build tree). Do not hand-edit; regenerate after changing mpi_bindings.cpp.
"""core Lagrangian halo (block decomposition + particle migration/ghosts)"""

from collections.abc import Sequence
from typing import Annotated

import numpy
from numpy.typing import NDArray


class ParticleMigrator:
    """
    Lagrangian particle migration over an ORB block decomposition of the box [origin, origin+extent) binned on `cells` cells per axis (MPI_COMM_WORLD). Positions are (N,3) float64, the per-particle payload (N,K) float64.
    """

    def __init__(self, origin: Sequence[float], extent: Sequence[float], cells: Sequence[int], periodic: Sequence[bool]) -> None:
        """
        origin: lower corner of the box; extent: its side lengths; cells: decomposition cells per axis (the ORB bins particles on this grid); periodic: per axis.
        """

    def migrate(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')]) -> tuple:
        """
        Reassign every particle to the rank owning its (wrapped) position; returns this rank's (positions (M,3), payload (M,K)) after the exchange.
        """

    def rebalance(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')]) -> tuple:
        """
        Re-decompose by particle count (weighted ORB) so each rank holds a near-equal share, then migrate. Pure redistribution (count/payload preserved); the partition is updated in place. Returns this rank's (positions (M,3), payload (M,K)).
        """

    def gather_ghosts(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], payload: Annotated[NDArray[numpy.float64], dict(order='C')], rcut: float) -> tuple:
        """
        Copies of particles within rcut of this rank's block (periodic images handled); returns the (ghost positions (G,3), ghost payload (G,K)).
        """

    def wrap_position(self, x: Sequence[float]) -> list[float]:
        """
        Periodic-wrapped / boundary-clamped position for x (the canonical image).
        """

    def cell_of(self, x: Sequence[float]) -> list[int]:
        """Global decomposition cell index (i,j,k) containing x (after wrap)."""

    def last_sent(self) -> int:
        """Particles shipped by this rank in the last migrate()."""

    def last_received(self) -> int:
        """Particles absorbed by this rank in the last migrate()."""

    def owner_of(self, x: Sequence[float]) -> int:
        """
        Rank that owns the block containing position x (after periodic wrap / boundary clamp).
        """

    @property
    def rank(self) -> int:
        """This process's MPI rank."""

class ParticleHalo:
    """
    Persistent owner<->ghost particle halo over the same decomposition as ParticleMigrator: build() the correspondence once, then forward/reverse Vec3 fields each step.
    """

    def __init__(self, origin: Sequence[float], extent: Sequence[float], cells: Sequence[int], periodic: Sequence[bool]) -> None:
        """
        origin: lower corner of the box; extent: its side lengths; cells: decomposition cells per axis (the ORB bins particles on this grid); periodic: per axis.
        """

    def build(self, positions: Annotated[NDArray[numpy.float64], dict(order='C')], rcut: float, include_periodic_self: bool = False) -> int:
        """
        Establish the owner<->ghost correspondence over this rank's owned positions
        """

    def forward_positions(self, owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """owned (N,3) -> ghost (G,3) with the periodic image shift (positions)"""

    def forward(self, owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """owned (N,3) -> ghost (G,3) verbatim (velocities, ...)"""

    def reverse(self, ghost: Annotated[NDArray[numpy.float64], dict(order='C')], owned: Annotated[NDArray[numpy.float64], dict(order='C')]) -> NDArray[numpy.float64]:
        """
        ghost (G,3) summed onto owned (N,3); returns owned + reversed contributions
        """

    def owner_of(self, x: Sequence[float]) -> int:
        """
        Rank that owns the block containing position x (after periodic wrap / boundary clamp).
        """

    @property
    def num_ghost(self) -> int:
        """
        Ghost particles this rank receives (G), as established by the last build().
        """

    @property
    def num_owned(self) -> int:
        """Owned particles (N) this rank passed to the last build()."""

    @property
    def rank(self) -> int:
        """This process's MPI rank."""
