# Type stubs for the tpx_amr pybind11 module (transport-core AMR octree).
#
# Editor/type-checker hints for the host AMR Python surface. Conventions: every per-leaf array is
# (num_leaves,) (or (num_leaves, k)) float64/int32/uint64 in the octree's Z-order slot order; world
# coordinates follow ../docs/CONVENTIONS.md. Keep in sync with python/tpx_amr.cpp.
from __future__ import annotations

from typing import Callable, Optional

import numpy as np
import numpy.typing as npt

F64 = npt.NDArray[np.float64]
I32 = npt.NDArray[np.int32]
U64 = npt.NDArray[np.uint64]
Bool = npt.NDArray[np.bool_]
Sdf = Callable[[float, float, float], float]

class Octree:
    """Serial single-block adaptive octree with a world placement (origin + finest spacing h0)."""

    def __init__(
        self,
        brick: list[int],
        lmax: int,
        origin: list[float] = ...,
        h0: float = ...,
    ) -> None: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def lmax(self) -> int: ...
    @property
    def h0(self) -> float: ...
    @property
    def origin(self) -> list[float]: ...
    def is_balanced(self) -> bool: ...
    def centers(self) -> F64: ...
    def sizes(self) -> F64: ...
    def levels(self) -> I32: ...
    def codes(self) -> U64: ...
    def find(self, x: list[float]) -> int: ...
    def refine_to_sphere(
        self,
        center: list[float],
        radius: float,
        target_level: int = ...,
        band: float = ...,
        balance: bool = ...,
    ) -> int: ...
    def refine_to_sdf(
        self, sdf: Sdf, target_level: int = ..., band: float = ..., balance: bool = ...
    ) -> int: ...
    def refine_leaf(self, i: int) -> bool: ...
    def balance(self) -> int: ...
    def lohner_indicator(self, field: F64, eps: float = ...) -> F64: ...
    def adapt(
        self,
        field: F64,
        refine_thresh: float,
        coarsen_thresh: float,
        finest_level: int = ...,
        eps: float = ...,
        linear: bool = ...,
    ) -> F64: ...
    def write_vtu(self, path: str, name: str, field: F64) -> None: ...

class Poisson:
    """Cell-centered FV Poisson solver (L u = rhs) on an Octree via a geometric-multigrid V-cycle."""

    def __init__(self, octree: Octree, periodic: bool = ...) -> None: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def num_levels(self) -> int: ...
    def apply(self, u: F64) -> F64: ...
    def residual(self, u: F64, rhs: F64) -> float: ...
    def solve(
        self,
        rhs: F64,
        x0: Optional[F64] = ...,
        cycles: int = ...,
        pre: int = ...,
        post: int = ...,
        tol: float = ...,
    ) -> tuple[F64, float, int]: ...

class Flow:
    """Collocated incompressible Stokes/Navier-Stokes step on an Octree with a cut-cell IBM."""

    def __init__(
        self, octree: Octree, density: float = ..., viscosity: float = ..., dt: float = ...
    ) -> None: ...
    @property
    def num_leaves(self) -> int: ...
    def set_solid(self, sdf: Sdf) -> None: ...
    def set_body_force(self, fx: float, fy: float, fz: float) -> None: ...
    def set_advection(self, on: bool) -> None: ...
    def set_advection_scheme(self, scheme: int) -> None: ...
    def set_implicit_advection(self, on: bool) -> None: ...
    def step(self, mom_sweeps: int = ..., pres_iters: int = ..., pres_sweeps: int = ...) -> None: ...
    def velocity(self, component: int) -> F64: ...
    def velocities(self) -> F64: ...
    def is_fluid(self) -> Bool: ...
    def divergence_norm(self) -> float: ...

class DistributedOctree:
    """MPI octree: an ORB block decomposition of a global root grid (one BlockOctree per rank)."""

    def __init__(
        self,
        global_root_size: list[int],
        lmax: int,
        origin: list[float] = ...,
        h0: float = ...,
        periodic: list[bool] = ...,
    ) -> None: ...
    @property
    def rank(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def num_leaves(self) -> int: ...
    @property
    def lmax(self) -> int: ...
    @property
    def h0(self) -> float: ...
    @property
    def block_origin_root(self) -> list[int]: ...
    @property
    def block_brick(self) -> list[int]: ...
    @property
    def global_root_size(self) -> list[int]: ...
    def centers(self) -> F64: ...
    def sizes(self) -> F64: ...
    def levels(self) -> I32: ...
    def codes(self) -> U64: ...
    def refine_to_sphere(
        self,
        center: list[float],
        radius: float,
        target_level: int = ...,
        band: float = ...,
        balance: bool = ...,
    ) -> int: ...
    def balance(self) -> int: ...
    def rebalance(self, fields: F64) -> F64: ...
    def face_neighbor_gather(self, field: F64, sentinel: float = ...) -> F64: ...
    def lohner_indicator(self, field: F64, eps: float = ...) -> F64: ...
    def adapt(
        self,
        field: F64,
        refine_thresh: float,
        coarsen_thresh: float,
        finest_level: int = ...,
        eps: float = ...,
        linear: bool = ...,
    ) -> F64: ...
    def write_vtu(self, path: str, name: str, field: F64) -> None: ...
